apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mimic
  name: mimic
  namespace: mimic
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mimic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mimic
    spec:
      containers:
      - image: mimic
        imagePullPolicy: IfNotPresent
        name: mimic
        ports:
          - containerPort: 8443
            name: api
        env:
          - name: MIMIC_LOGLEVEL
            value: debug
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      serviceAccount: mimic
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
