apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mimic
  namespace: mimic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mimic
subjects:
- kind: ServiceAccount
  name: mimic
  namespace: mimic
