apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mimic
  labels:
    app: mimic
webhooks:
- name: mimic.cryptkcoding.com
  clientConfig:
    service:
      name: mimic
      namespace: mimic
      path: "/mutate"
      port: 8443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJd01EY3hOREl3TWpZMU1Gb1hEVE13TURjeE16SXdNalkxTUZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVBYClFKaDROYnFzTm9LNklUcTRBam1nSEsyd3VnQm9OTDhoU3RFRXJra1lQYU9JcmdEVlV0MlAxaklGclUwRHVnL3cKYkltNnF3QkMxQzROcmtDb3ZBTkN0T3plTmM0S0xWK3dxTHpLYk41WjVOdDBuWXR6MHFpcVprZnI5NkYxZ0pUNAo4bmpNSE9nUGp0MnRXSEptMmhXV2M5TnFEaUkweC9IZnh6SnI3WHlYZ0ZZclJHa2tNeUpDWE1WS0JPYlJieC9BCkFyeFNlYm9pSmN4Zi8xTUdSK3M2Z08wWjQzL1B3SWNxb3lPZ1lYNUQ0V1FDeU1sUmM3RzZFenFjQVdjMXV2djMKZnNTR2x0cnBPSUVFZE9YZFBhWThCTWNVUjAxMzZRR1dCcEticVpZdTNJcnFVUndpdGkyNG1maGREMUNIb0dFRwpPUXB6Mm5HQmdjV010UFRjeGhVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBaVJlbG4yM3lpLzNSaVJpMFlGaHVtSVRuVDlTL011R05tdzBqWHhjMmE3UUk2NnZwRQp1M3hCVUQ3V3BFeUZOTGEwK2hBbHpsS1cvZXUvWWgxaE90RVpicnpXOXdqZHNGdWpLdTdMQ0FTNHNwRXZnZTFHClRjcFplUTNObmNWcVI4WVM3WVhzVDFoanFsS2hGeTFhdk5zN09Bd09IYzVyYmFmSDJ2NEMwUXhzcmY1S0hYUEIKanpSQmVSaE5RSmtkLzNYK0hHMkRuQnVLTWlVdG9CNlp0MVZCUFZhbnNRT1lFNUNVVE1qSTlWbE5QRTFhMVR1dgpDekh4WkJ0b2xoYXhYVzJqYi9lbHZxa2pkdjRCWWo5RGRKb1lhY1NoOEY0c2VZaGczdGZJUTh3cGYxOE9rUnM4ClNVcEF6MWc2SFlmaWNFWUp5SGhjZVJJbzZqc3Z5TDVzbW5iQgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  failurePolicy: Ignore
  sideEffects: None
